import { useState, useEffect } from "react";
import ConfirmCancelButton from "../../confirm-cancel-button/confirm_cancel_button";
import EditLocationInformation from "./edit_location_information";
import CreateLocationInformation from "./create_location_information";

export default function FetchLocationInformation(props) {
  const { selectedLocation, buttonType, switchShowModal, selectedFloor } =
    props ?? {};
  const baseURL = `http://marco.cooldev.win:8080/api/v1`;

  const [getLocationName, setGetLocationName] = useState("");
  const [getLocationGeoX, setGetLocationGeoX] = useState("");
  const [getLocationGeoY, setGetLocationGeoY] = useState("");

  const [userConfirm, setUserConfirm] = useState(false);

  const fetchInfo = async () => {
    return await fetch(baseURL + `/locations` + "/" + selectedLocation)
      .then((e) => e.json())
      .then((d) => JSON.parse(JSON.stringify(d)))
      .then((f) => {
        setGetLocationName(f.name);
        setGetLocationGeoX(f.geoX);
        setGetLocationGeoY(f.geoY);
      });
  };

  const handleNameChange = (event) => {
    setGetLocationName(event.target.value);
  };
  const handleGeoXChange = (event) => {
    setGetLocationGeoX(event.target.value);
  };
  const handleGeoYChange = (event) => {
    setGetLocationGeoY(event.target.value);
  };

  const checkUserInput = () => {
    if (
      getLocationName != "" &&
      getLocationGeoX != "" &&
      getLocationGeoY != ""
    ) {
      return true;
    }
    return false;
  };

  useEffect(() => {
    if (userConfirm === true && checkUserInput() == true) {
      if (buttonType === "create") {
        CreateLocationInformation(
          getLocationName,
          getLocationGeoX,
          getLocationGeoY,
          selectedFloor
        );
      } else if (buttonType === "edit") {
        EditLocationInformation(
          selectedLocation,
          getLocationName,
          getLocationGeoX,
          getLocationGeoY
        );
      }
      switchShowModal();
    }
    setUserConfirm(false);
  }, [userConfirm]);

  useEffect(() => {
    if (buttonType === "edit") {
      fetchInfo();
    } else if (buttonType === "create") {
      console.log("Create Section");
    } else {
      console.log("Delete Section");
    }
  }, []);

  return (
    <div>
      <div className="location-id-header">
        {buttonType === "create"
          ? "LOCATION ID AUTOGENERATED"
          : "FLOOR ID " + selectedLocation}
      </div>
      <div className="location-input-configuration">
        LOCATION NAME{" "}
        <input
          defaultValue={buttonType === "create" ? null : getLocationName}
          onChange={handleNameChange}
        ></input>
      </div>
      <div className="location-input-configuration">
        GEO X
        <input
          defaultValue={buttonType === "create" ? null : getLocationGeoX}
          onChange={handleGeoXChange}
        ></input>
      </div>
      <div className="location-input-configuration">
        GEO Y
        <input
          defaultValue={buttonType === "create" ? null : getLocationGeoY}
          onChange={handleGeoYChange}
        ></input>
      </div>
      <ConfirmCancelButton
        setUserConfirm={setUserConfirm}
        switchShowModal={switchShowModal}
      />
    </div>
  );
}
