import { useState, useEffect } from "react";

export default function FetchBeaconInformation(props) {
  const { selectedBeacon, buttonType } = props ?? {};
  const baseURL = `http://marco.cooldev.win:8080/api/v1`;

  const [getBeaconName, setGetBeaconName] = useState("");
  const [getBeaconGeoX, setGetBeaconGeoX] = useState("");
  const [getBeaconGeoY, setGetBeaconGeoY] = useState("");
  const [getMacAddress, setGetMacAddress] = useState("");

  const fetchInfo = async () => {
    return await fetch(baseURL + `/beacons` + "/" + selectedBeacon)
      .then((e) => e.json())
      .then((d) => JSON.parse(JSON.stringify(d)))
      .then((f) => {
        setGetBeaconName(f.name);
        setGetBeaconGeoX(f.geoX);
        setGetBeaconGeoY(f.geoY);
        setGetMacAddress(f.macAddress);
      });
  };

  useEffect(() => {
    if (buttonType === "edit") {
      fetchInfo();
    }
  }, []);

  return (
    <div>
        <div className="beacon-id-header">
          {buttonType === "create" ? "BEACON ID AUTOGENERATED" : "BEACON ID " + selectedBeacon}
        </div>
      <div className="beacon-input-configuration">
        BEACON NAME
        <input
          defaultValue={buttonType === "create" ? null : getBeaconName}
        ></input>
      </div>
      <div className="beacon-input-configuration">
        GEO X
        <input
          defaultValue={buttonType === "create" ? null : getBeaconGeoX}
        ></input>
      </div>
      <div className="beacon-input-configuration">
        GEO Y
        <input
          defaultValue={buttonType === "create" ? null : getBeaconGeoY}
        ></input>
      </div>
      <div className="beacon-input-configuration">
        BEACON MAC-ADDRESS
        <input
          defaultValue={buttonType === "create" ? null : getMacAddress}
        ></input>
      </div>
    </div>
  );
}
