import "./modal_page_floor.css";
import { useState } from "react";
import modalPageFloorLocation from "./floor/floor_location/modal_page_floor_location";

export default function ModalPageFloor(props) {
  const { selectedFloor, buttonType } = props ?? {};

  const [fetchFloorName, setFetchFloorName] = useState("");
  const [fetchGeoLength, setFetchGeoLength] = useState("");
  const [fetchGeoWidth, setFetchGeoWidth] = useState("");
  const [fetchAzimuth, setFetchAzimuth] = useState("");

  return (
    <div id="modal-page-floor-main">
      <div className="modal-page-container">
        <div className="floor-id-header">
          {buttonType === "create"
            ? "FLOOR ID AUTOGENERATED"
            : "FLOOR ID " + selectedFloor}
        </div>
        <div className="floor-input-configuration">
          FLOOR NAME{" "}
          <input value={buttonType === "create" ? null : fetchFloorName}></input>
        </div>
        <div className="floor-input-configuration">
          GEO LENGTH{" "}
          <input value={buttonType === "create" ? null : fetchGeoLength}></input>
        </div>
        <div className="floor-input-configuration">
          GEO WIDTH{" "}
          <input value={buttonType === "create" ? null : fetchGeoWidth}></input>
        </div>
        <div className="floor-input-configuration">
          AZIMUTH{" "}
          <input value={buttonType === "create" ? null : fetchAzimuth}></input>
        </div>
      </div>
      <div id="modal-page-floor-component">
        {modalPageFloorLocation()}
        <div id="modal-page-floor-beacon"></div>
        <div id="modal-page-floor-file"></div>
      </div>
    </div>
  );
}
