import "./modal_page_beacon.css";
import { useState } from "react";
import modalPageBeaconFloor from "./beacon/beacon_floor/modal_page_beacon_floor";

export default function modalPageBeacon(props) {
  const { selectedBeacon, buttonType } = props ?? {};

  const [fetchBeaconName, setFetchBeaconName] = useState("");
  const [fetchBeaconGeoX, setFetchBeaconGeoX] = useState("");
  const [fetchBeaconGeoY, setFetchBeaconGeoY] = useState("");
  const [fetchMacAddress, setFetchMacAddress] = useState("");

  return (
    <div id="modal-page-beacon-main">
      <div className="modal-page-container">
        <div className="beacon-id-header">
          {buttonType === "create" ? "BEACON ID AUTOGENERATED" : "BEACON ID " + selectedBeacon}
        </div>
        <div className="beacon-id-header">
          {buttonType === "create" ? "BEACON MAC-ADDRESS AUTOGENERATED" : "MAC-ADDRESS " + fetchMacAddress}
        </div>
        <div className="beacon-input-configuration">
          BEACON NAME
          <input value={buttonType === "create" ? null : fetchBeaconName}></input>
        </div>
        <div className="beacon-input-configuration">
          GEO X
          <input value={buttonType === "create" ? null : fetchBeaconGeoX}></input>
        </div>
        <div className="beacon-input-configuration">
          GEO Y
          <input value={buttonType === "create" ? null : fetchBeaconGeoY}></input>
        </div>
      </div>
      <div id="modal-page-beacon-component">
        {modalPageBeaconFloor()}
        <div id="modal-page-beacon-beacon"></div>
        <div id="modal-page-beacon-file"></div>
      </div>
    </div>
  );
}
