import "./modal_page_location.css";
import { useState } from "react";
import modalPageLocationFloor from "./location/location_floor/modal_page_location_floor";

export default function modalPageLocation(props) {
  const { selectedLocation, buttonType } = props ?? {};

  const [fetchLocationName, setFetchLocationName] = useState("");
  const [fetchLocationGeoX, setFetchLocationGeoX] = useState("");
  const [fetchLocationGeoY, setFetchLocationGeoY] = useState("");

  return (
    <div id="modal-page-location-main">
      <div className="modal-page-container">
        <div className="location-id-header">
          {buttonType === "create" ? "LOCATION ID AUTOGENERATED" : "FLOOR ID " + selectedLocation}
        </div>
        <div className="location-input-configuration">
          LOCATION NAME{" "}
          <input value={buttonType === "create" ? null : fetchLocationName}></input>
        </div>
        <div className="location-input-configuration">
          GEO X
          <input value={buttonType === "create" ? null : fetchLocationGeoX}></input>
        </div>
        <div className="location-input-configuration">
          GEO Y
          <input value={buttonType === "create" ? null : fetchLocationGeoY}></input>
        </div>
      </div>
      <div id="modal-page-location-component">
        {modalPageLocationFloor()}
        <div id="modal-page-location-beacon"></div>
        <div id="modal-page-location-file"></div>
      </div>
    </div>
  );
}
