import "./modal_page_location.css"
import modalPageLocationFloor from "./location/location_floor/modal_page_location_floor"

export default function modalPageLocation(selectedLocation, buttonType){

    return (
        <div id="modal-page-location-main">
            <div className="modal-page-container">
                <div className="location-id-header">{buttonType === "create" ? ("LOCATION ID AUTOGENERATED") : ("LOCATION ID " + selectedLocation)}</div>
                <div className="location-input-configuration">
                    LOCATION NAME <input></input>
                </div>
                <div className="location-input-configuration">
                    GEO LENGTH <input></input>
                </div>
                <div className="location-input-configuration">
                    GEO WIDTH <input></input>
                </div>
            </div>
            <div id="modal-page-location-component">
                {modalPageLocationFloor()}
            </div>
        </div>
    )
}