import "./modal_page_beacon.css";
import { useState } from "react";
import modalPageBeaconFloor from "./beacon/beacon_floor/modal_page_beacon_floor";

export default function modalPageBeacon(props) {
  const { selectedBeacon, buttonType } = props ?? {};

  const [getBeaconName, setGetBeaconName] = useState("");
  const [getBeaconGeoX, setGetBeaconGeoX] = useState("");
  const [getBeaconGeoY, setGetBeaconGeoY] = useState("");
  const [getMacAddress, setGetMacAddress] = useState("");

  return (
    <div id="modal-page-beacon-main">
      <div className="modal-page-container">
        <div className="beacon-id-header">
          {buttonType === "create" ? "BEACON ID AUTOGENERATED" : "BEACON ID " + selectedBeacon}
        </div>
        <div className="beacon-id-header">
          {buttonType === "create" ? "BEACON MAC-ADDRESS AUTOGENERATED" : "MAC-ADDRESS " + getMacAddress}
        </div>
        <div className="beacon-input-configuration">
          BEACON NAME
          <input defaultValue={buttonType === "create" ? null : getBeaconName}></input>
        </div>
        <div className="beacon-input-configuration">
          GEO X
          <input defaultValue={buttonType === "create" ? null : getBeaconGeoX}></input>
        </div>
        <div className="beacon-input-configuration">
          GEO Y
          <input defaultValue={buttonType === "create" ? null : getBeaconGeoY}></input>
        </div>
      </div>
      <div id="modal-page-beacon-component">
        {modalPageBeaconFloor()}
        <div id="modal-page-beacon-beacon"></div>
        <div id="modal-page-beacon-file"></div>
      </div>
    </div>
  );
}
